[project]
name = "codes-python"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib",
    "numpy",
    "pandas",
    "scipy",
    "tqdm",
    "pyproj",
    "cartopy",
    "geopy",
    "netCDF4",
]
